setup.py: Add missing dependency (#57)
Without this I got the following error while running inside a virtual
environment with python 3.12:

ModuleNotFoundError: No module named 'pkg_resources'

Signed-off-by: Jinank Jain <jinank94@gmail.com>